// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: meta/meta_type.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetaType message.
type MetaType int32

const (
	MetaType_Unknown   MetaType = 0
	MetaType_Directory MetaType = 1
	MetaType_Image     MetaType = 2
	MetaType_Video     MetaType = 3
	MetaType_Audio     MetaType = 4
	MetaType_Document  MetaType = 5
	MetaType_Archive   MetaType = 6
)

// Enum value maps for MetaType.
var (
	MetaType_name = map[int32]string{
		0: "Unknown",
		1: "Directory",
		2: "Image",
		3: "Video",
		4: "Audio",
		5: "Document",
		6: "Archive",
	}
	MetaType_value = map[string]int32{
		"Unknown":   0,
		"Directory": 1,
		"Image":     2,
		"Video":     3,
		"Audio":     4,
		"Document":  5,
		"Archive":   6,
	}
)

func (x MetaType) Enum() *MetaType {
	p := new(MetaType)
	*p = x
	return p
}

func (x MetaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetaType) Descriptor() protoreflect.EnumDescriptor {
	return file_meta_meta_type_proto_enumTypes[0].Descriptor()
}

func (MetaType) Type() protoreflect.EnumType {
	return &file_meta_meta_type_proto_enumTypes[0]
}

func (x MetaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetaType.Descriptor instead.
func (MetaType) EnumDescriptor() ([]byte, []int) {
	return file_meta_meta_type_proto_rawDescGZIP(), []int{0}
}

var File_meta_meta_type_proto protoreflect.FileDescriptor

var file_meta_meta_type_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x2a, 0x62, 0x0a, 0x08,
	0x4d, 0x65, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x10, 0x06,
	0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_meta_meta_type_proto_rawDescOnce sync.Once
	file_meta_meta_type_proto_rawDescData = file_meta_meta_type_proto_rawDesc
)

func file_meta_meta_type_proto_rawDescGZIP() []byte {
	file_meta_meta_type_proto_rawDescOnce.Do(func() {
		file_meta_meta_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_meta_type_proto_rawDescData)
	})
	return file_meta_meta_type_proto_rawDescData
}

var file_meta_meta_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meta_meta_type_proto_goTypes = []interface{}{
	(MetaType)(0), // 0: meta.MetaType
}
var file_meta_meta_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_meta_type_proto_init() }
func file_meta_meta_type_proto_init() {
	if File_meta_meta_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_meta_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_meta_type_proto_goTypes,
		DependencyIndexes: file_meta_meta_type_proto_depIdxs,
		EnumInfos:         file_meta_meta_type_proto_enumTypes,
	}.Build()
	File_meta_meta_type_proto = out.File
	file_meta_meta_type_proto_rawDesc = nil
	file_meta_meta_type_proto_goTypes = nil
	file_meta_meta_type_proto_depIdxs = nil
}
